### ISSUE TITLE
Switch from Cabal file Extensions field to per-file LANGUAGE pragmas

### ISSUE THREAD

**Issue by nh2** [haskell-distributed/distributed-process#248] opened 2015-07-05 15:50 UTC
The `Extensions:` field in `.cabal` files makes it difficult to work with `ghci` and other non-cabal tools.

Could we switch to per-file `{-# LANGUAGE ... #-}` pragmas for the CloudHaskell packages?

Thanks!

**Comment by qnikst** [comment] 2015-07-05 15:51
Yes, will be done soon.

**Comment by nh2** [comment] 2015-07-05 15:53
Nice.

**Comment by mboes** [comment] 2015-07-06 20:32
@nh2 agreed. But note that `stack ghci distributed-process`, from the [haskell-distributed/cloud-haskell](https://github.com/haskell-distributed/cloud-haskell) repo should work just fine, even now.

**Comment by mboes** [comment] 2015-07-06 20:36
In fact, this was already done. Closing as a duplicate of https://github.com/haskell-distributed/distributed-process/pull/151. Unless you mean other packages? In which you should file a bug report against those. Or better yet, submit a PR. :)

**Closed by mboes** 2015-07-06 20:36 UTC
